services:
  edgeyolo_ros_onnxruntime:
    container_name: edgeyolo_onnxruntime
    build:
      context: .
      args:
        - BASE_TAB=12.1.0-cudnn8-devel-ubuntu22.04
    image: okdhryk/onnxruntime_edgeyolo_ros:latest
    network_mode: host
    gpus: all
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/ros2_ws:/root/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    working_dir: /root/ros2_ws
    tty: true
    command: bash
